export default {
  board: {
    source: null,
    target: null,
    tiles: [
      // Row 0
      { index: 0, x: 0, y: 0, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 1, x: 0, y: 1, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 2, x: 0, y: 2, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 3, x: 0, y: 3, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 4, x: 0, y: 4, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 5, x: 0, y: 5, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 6, x: 0, y: 6, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 7, x: 0, y: 7, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 8, x: 0, y: 8, type: 5, source: false, matchedX: false, matchedY: false },
      // Row 1
      { index: 9, x: 1, y: 0, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 10, x: 1, y: 1, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 11, x: 1, y: 2, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 12, x: 1, y: 3, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 13, x: 1, y: 4, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 14, x: 1, y: 5, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 15, x: 1, y: 6, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 16, x: 1, y: 7, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 17, x: 1, y: 8, type: 5, source: false, matchedX: false, matchedY: false },
      // Row 2
      { index: 18, x: 2, y: 0, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 19, x: 2, y: 1, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 20, x: 2, y: 2, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 21, x: 2, y: 3, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 22, x: 2, y: 4, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 23, x: 2, y: 5, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 24, x: 2, y: 6, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 25, x: 2, y: 7, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 26, x: 2, y: 8, type: 3, source: false, matchedX: false, matchedY: false },
      // Row 3
      { index: 27, x: 3, y: 0, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 28, x: 3, y: 1, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 29, x: 3, y: 2, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 30, x: 3, y: 3, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 31, x: 3, y: 4, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 32, x: 3, y: 5, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 33, x: 3, y: 6, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 34, x: 3, y: 7, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 35, x: 3, y: 8, type: 1, source: false, matchedX: false, matchedY: false },
      // Row 4
      { index: 36, x: 4, y: 0, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 37, x: 4, y: 1, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 38, x: 4, y: 2, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 39, x: 4, y: 3, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 40, x: 4, y: 4, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 41, x: 4, y: 5, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 42, x: 4, y: 6, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 43, x: 4, y: 7, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 44, x: 4, y: 8, type: 5, source: false, matchedX: false, matchedY: false },
      // Row 5
      { index: 45, x: 5, y: 0, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 46, x: 5, y: 1, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 47, x: 5, y: 2, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 48, x: 5, y: 3, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 49, x: 5, y: 4, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 50, x: 5, y: 5, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 51, x: 5, y: 6, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 52, x: 5, y: 7, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 53, x: 5, y: 8, type: 3, source: false, matchedX: false, matchedY: false },
      // Row 6
      { index: 54, x: 6, y: 0, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 55, x: 6, y: 1, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 56, x: 6, y: 2, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 57, x: 6, y: 3, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 58, x: 6, y: 4, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 59, x: 6, y: 5, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 60, x: 6, y: 6, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 61, x: 6, y: 7, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 62, x: 6, y: 8, type: 5, source: false, matchedX: false, matchedY: false },
      // Row 7
      { index: 63, x: 7, y: 0, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 64, x: 7, y: 1, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 65, x: 7, y: 2, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 66, x: 7, y: 3, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 67, x: 7, y: 4, type: 5, source: false, matchedX: false, matchedY: false },
      { index: 68, x: 7, y: 5, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 69, x: 7, y: 6, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 70, x: 7, y: 7, type: 3, source: false, matchedX: false, matchedY: false },
      { index: 71, x: 7, y: 8, type: 4, source: false, matchedX: false, matchedY: false },
      // Row 8
      { index: 72, x: 8, y: 0, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 73, x: 8, y: 1, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 74, x: 8, y: 2, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 75, x: 8, y: 3, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 76, x: 8, y: 4, type: 1, source: false, matchedX: false, matchedY: false },
      { index: 77, x: 8, y: 5, type: 4, source: false, matchedX: false, matchedY: false },
      { index: 78, x: 8, y: 6, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 79, x: 8, y: 7, type: 2, source: false, matchedX: false, matchedY: false },
      { index: 80, x: 8, y: 8, type: 1, source: false, matchedX: false, matchedY: false }
    ]
  }
}
